services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
