# Generated by Django 6.0.7 on 2026-07-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinycontent', '0005_auto_20240221_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinycontent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tinycontent',
            name='autocreated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='tinycontent',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tinycontent',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TinyContentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_path', models.CharField(max_length=500)),
                ('line_number', models.PositiveIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='tinycontent.tinycontent')),
            ],
            options={
                'verbose_name': 'Template usage',
                'verbose_name_plural': 'Template usages',
                'ordering': ('template_path', 'line_number'),
                'constraints': [models.UniqueConstraint(fields=('content', 'template_path', 'line_number'), name='unique_tinycontent_usage')],
            },
        ),
    ]
